# Generated by Django 2.2.7 on 2019-12-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191123_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Time', models.TimeField()),
                ('booked_seats', models.IntegerField()),
            ],
        ),
    ]
