# Generated by Django 2.2.7 on 2019-12-03 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bookingsummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookingSummary',
        ),
    ]
