# Generated by Django 2.2.7 on 2019-12-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='amount_paid',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
