# Generated by Django 2.2.7 on 2019-12-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191204_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='account_number',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
