# Generated by Django 2.2.7 on 2019-12-09 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_booking_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='account_number',
        ),
    ]
